apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- prometheus/configmap.yaml
- prometheus/servicemonitors/kustomization.yaml
- prometheus/prometheusrules/kustomization.yaml
- grafana/dashboard-provisioning.yaml
- grafana/dashboards/standard/k8s-cluster-monitoring.yaml
- grafana/dashboards/standard/node-exporter-full.yaml
- grafana/dashboards/standard/k8s-pods.yaml
- grafana/dashboards/standard/k8s-deployment.yaml
- grafana/dashboards/standard/k8s-kubelet.yaml
- grafana/dashboards/standard/prometheus-stats.yaml
- grafana/dashboards/standard/prometheus-2-stats.yaml
- grafana/dashboards/standard/alertmanager.yaml
- grafana/dashboards/standard/nginx-ingress.yaml
- grafana/dashboards/custom/infrastructure-overview.yaml
- alertmanager/kustomization.yaml
- node-exporter/kustomization.yaml
- kube-state-metrics/kustomization.yaml
