apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- prometheus/serviceaccount.yaml
- prometheus/clusterrole.yaml
- prometheus/clusterrolebinding.yaml
- prometheus/configmap.yaml
- prometheus/servicemonitors/coredns.yaml
- prometheus/servicemonitors/cert-manager.yaml
- prometheus/servicemonitors/nginx-ingress.yaml
- prometheus/servicemonitors/argocd.yaml
- prometheus/servicemonitors/argocd-server.yaml
- prometheus/servicemonitors/argocd-application-controller.yaml
- prometheus/servicemonitors/argocd-repo-server.yaml
- prometheus/servicemonitors/argocd-dex-server.yaml
- prometheus/servicemonitors/velero.yaml
- prometheus/servicemonitors/kubelet.yaml
- prometheus/servicemonitors/alertmanager.yaml
- prometheus/servicemonitors/node-exporter.yaml
- prometheus/servicemonitors/kube-state-metrics.yaml
- prometheus/prometheusrules/kubernetes.yaml
- prometheus/prometheusrules/services.yaml
- prometheus/prometheusrules/infrastructure.yaml
- grafana/dashboard-provisioning.yaml
- grafana/dashboards/standard/prometheus-stats.yaml
- grafana/dashboards/standard/alertmanager.yaml
- grafana/dashboards/standard/node-exporter.yaml
- grafana/dashboards/standard/kubernetes-cluster.yaml
- grafana/dashboards/custom/infrastructure-overview.yaml
- grafana/dashboards/custom/argocd-overview.yaml
- grafana/dashboards/custom/coredns-overview.yaml
- grafana/dashboards/custom/nginx-ingress.yaml
- grafana/dashboards/custom/cert-manager.yaml
- grafana/dashboards/custom/velero.yaml
- grafana/dashboards/custom/resource-usage.yaml
- grafana/dashboards/custom/services-overview.yaml
- grafana/dashboards/custom/replicaset-overview.yaml
- grafana/dashboards/custom/daemonset-overview.yaml
- grafana/dashboards/custom/statefulset-overview.yaml
- grafana/dashboards/custom/pvc-overview.yaml
- alertmanager/namespace.yaml
- alertmanager/configmap.yaml
- alertmanager/pvc.yaml
- alertmanager/deployment.yaml
- alertmanager/service.yaml
- alertmanager/certificate.yaml
- alertmanager/ingress.yaml
- node-exporter/namespace.yaml
- node-exporter/daemonset.yaml
- node-exporter/service.yaml
- kube-state-metrics/namespace.yaml
- kube-state-metrics/serviceaccount.yaml
- kube-state-metrics/clusterrole.yaml
- kube-state-metrics/clusterrolebinding.yaml
- kube-state-metrics/deployment.yaml
- kube-state-metrics/service.yaml
