apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  TZ: "Europe/Berlin"
  WEBPASSWORD: ""  # Wird später über Secret gesetzt
  PIHOLE_DNS_: "1.1.1.1;1.0.0.1"  # Cloudflare DNS
  DNSSEC: "true"
  DNSMASQ_LISTENING: "all"
  DNSMASQ_USER: "root"
  VIRTUAL_HOST: "pihole.k8sops.online"
  ServerIP: "192.168.178.10"

