apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-k8sops-online-tls
  namespace: default
spec:
  secretName: jellyfin-k8sops-online-tls
  issuerRef:
    name: letsencrypt-prod-dns01
    kind: ClusterIssuer
  dnsNames:
  - jellyfin.k8sops.online

