apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-prod-dns01","nginx.ingress.kubernetes.io/ssl-redirect":"true"},"name":"syncthing-ingress","namespace":"syncthing"},"spec":{"ingressClassName":"nginx","rules":[{"host":"syncthing.k8sops.online","http":{"paths":[{"backend":{"service":{"name":"syncthing-ui","port":{"number":8384}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["syncthing.k8sops.online"],"secretName":"syncthing-k8sops-online-tls"}]}}

      '
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: syncthing-ingress
  namespace: syncthing
spec:
  ingressClassName: nginx
  rules:
  - host: syncthing.k8sops.online
    http:
      paths:
      - backend:
          service:
            name: syncthing-ui
            port:
              number: 8384
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - syncthing.k8sops.online
    secretName: syncthing-k8sops-online-tls
