apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"syncthing","namespace":"syncthing"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"syncthing"}},"serviceName":"syncthing-headless","template":{"metadata":{"labels":{"app":"syncthing"}},"spec":{"containers":[{"env":[{"name":"PUID","value":"1000"},{"name":"PGID","value":"1000"}],"image":"syncthing/syncthing:latest","name":"syncthing","ports":[{"containerPort":8384,"name":"web"},{"containerPort":22000,"name":"sync"},{"containerPort":21027,"name":"discovery"}],"volumeMounts":[{"mountPath":"/var/syncthing/config","name":"syncthing-config"},{"mountPath":"/var/syncthing/data","name":"syncthing-data"},{"mountPath":"/wolke","name":"syncthing-wolke"}]}],"volumes":[{"name":"syncthing-config","persistentVolumeClaim":{"claimName":"syncthing-config"}},{"name":"syncthing-data","persistentVolumeClaim":{"claimName":"syncthing-data"}},{"name":"syncthing-wolke","persistentVolumeClaim":{"claimName":"syncthing-wolke"}}]}}}}

      '
  name: syncthing
  namespace: syncthing
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: syncthing
  serviceName: syncthing-headless
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
      - env:
        - name: PUID
          value: '1000'
        - name: PGID
          value: '1000'
        image: syncthing/syncthing:latest
        imagePullPolicy: Always
        name: syncthing
        ports:
        - containerPort: 8384
          name: web
          protocol: TCP
        - containerPort: 22000
          name: sync
          protocol: TCP
        - containerPort: 21027
          name: discovery
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/syncthing/config
          name: syncthing-config
        - mountPath: /var/syncthing/data
          name: syncthing-data
        - mountPath: /wolke
          name: syncthing-wolke
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: syncthing-config
        persistentVolumeClaim:
          claimName: syncthing-config
      - name: syncthing-data
        persistentVolumeClaim:
          claimName: syncthing-data
      - name: syncthing-wolke
        persistentVolumeClaim:
          claimName: syncthing-wolke
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
