apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heimdall
  namespace: argocd
  labels:
    app: heimdall
spec:
  project: default
  source:
    repoURL: https://github.com/bernd-lab/heimnetzwerk-infra.git
    targetRevision: main
    path: k8s/heimdall
  destination:
    server: https://kubernetes.default.svc
    namespace: heimdall
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10

