apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
  labels:
    app: komga
spec:
  project: default
  source:
    repoURL: https://github.com/bernd-lab/heimnetzwerk-infra.git
    targetRevision: main
    path: k8s/komga
  destination:
    server: https://kubernetes.default.svc
    namespace: komga
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 10

