apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '6'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"komga","namespace":"komga"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"komga"}},"template":{"metadata":{"labels":{"app":"komga"}},"spec":{"containers":[{"env":[{"name":"SERVER_PORT","value":"25600"}],"image":"gotson/komga:1.21.3","name":"komga","ports":[{"containerPort":25600}],"volumeMounts":[{"mountPath":"/config","name":"komga-config"},{"mountPath":"/data","name":"komga-data"},{"mountPath":"/media/elements","name":"komga-media-elements"},{"mountPath":"/media/wdblack","name":"komga-media-wdblack"}]}],"volumes":[{"name":"komga-config","persistentVolumeClaim":{"claimName":"komga-config"}},{"name":"komga-data","persistentVolumeClaim":{"claimName":"komga-data"}},{"name":"komga-media-elements","persistentVolumeClaim":{"claimName":"komga-media-elements"}},{"name":"komga-media-wdblack","persistentVolumeClaim":{"claimName":"komga-media-wdblack"}}]}}}}

      '
  name: komga
  namespace: komga
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: komga
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: komga
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: '25600'
        image: gotson/komga:1.21.3
        imagePullPolicy: IfNotPresent
        name: komga
        ports:
        - containerPort: 25600
          protocol: TCP
        resources:
          limits:
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: komga-config
        - mountPath: /data
          name: komga-data
        - mountPath: /media/elements
          name: komga-media-elements
        - mountPath: /media/wdblack
          name: komga-media-wdblack
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: komga-config
        persistentVolumeClaim:
          claimName: komga-config
      - name: komga-data
        persistentVolumeClaim:
          claimName: komga-data
      - name: komga-media-elements
        persistentVolumeClaim:
          claimName: komga-media-elements
      - name: komga-media-wdblack
        persistentVolumeClaim:
          claimName: komga-media-wdblack
