apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt-prod-dns01","nginx.ingress.kubernetes.io/ssl-redirect":"true"},"name":"komga-ingress","namespace":"komga"},"spec":{"ingressClassName":"nginx","rules":[{"host":"komga.k8sops.online","http":{"paths":[{"backend":{"service":{"name":"komga","port":{"number":25600}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["komga.k8sops.online"],"secretName":"komga-k8sops-online-tls"}]}}

      '
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  name: komga-ingress
  namespace: komga
spec:
  ingressClassName: nginx
  rules:
  - host: komga.k8sops.online
    http:
      paths:
      - backend:
          service:
            name: komga
            port:
              number: 25600
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - komga.k8sops.online
    secretName: komga-k8sops-online-tls
