apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"komga","namespace":"komga"},"spec":{"ports":[{"port":25600,"targetPort":25600}],"selector":{"app":"komga"},"type":"ClusterIP"}}

        '
    creationTimestamp: '2025-11-03T11:19:03Z'
    name: komga
    namespace: komga
    resourceVersion: '95580'
    uid: c9e7de15-8154-466b-ba2f-e0535aa43e70
  spec:
    clusterIP: 10.108.252.250
    clusterIPs:
    - 10.108.252.250
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 25600
      protocol: TCP
      targetPort: 25600
    selector:
      app: komga
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
