apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '15'
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"gitlab","namespace":"gitlab"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"gitlab"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"gitlab"}},"spec":{"containers":[{"env":[{"name":"GITLAB_OMNIBUS_CONFIG","valueFrom":{"configMapKeyRef":{"key":"gitlab.rb","name":"gitlab-config"}}}],"image":"gitlab/gitlab-ce:latest","livenessProbe":{"failureThreshold":10,"httpGet":{"httpHeaders":[{"name":"Host","value":"gitlab.k8sops.online"}],"path":"/-/health","port":80},"initialDelaySeconds":200,"periodSeconds":10,"timeoutSeconds":5},"name":"gitlab","ports":[{"containerPort":80,"name":"http"},{"containerPort":22,"name":"ssh"}],"readinessProbe":{"exec":{"command":["/bin/bash","-c","curl
      -sf http://localhost:80/-/readiness -H \"Host: gitlab.k8sops.online\" \u003e
      /dev/null"]},"failureThreshold":30,"initialDelaySeconds":60,"periodSeconds":10,"timeoutSeconds":5},"resources":{"limits":{"cpu":"2000m","memory":"5Gi"},"requests":{"cpu":"500m","memory":"3Gi"}},"volumeMounts":[{"mountPath":"/var/opt/gitlab","name":"gitlab-data"},{"mountPath":"/etc/gitlab","name":"gitlab-config"}]}],"nodeSelector":{"workload-type":"production"},"volumes":[{"name":"gitlab-data","persistentVolumeClaim":{"claimName":"gitlab-data"}},{"name":"gitlab-config","persistentVolumeClaim":{"claimName":"gitlab-config"}}]}}}}

      '
  name: gitlab
  namespace: gitlab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: '2025-11-05T18:21:32+01:00'
      labels:
        app: gitlab
    spec:
      containers:
      - env:
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              key: gitlab.rb
              name: gitlab-config
        image: gitlab/gitlab-ce:latest
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - curl -sf http://localhost:80/-/health > /dev/null
          failureThreshold: 12
          initialDelaySeconds: 600
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: gitlab
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 22
          name: ssh
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - 'curl -sf http://localhost:80/-/readiness -H "Host: gitlab.k8sops.online"
              > /dev/null'
          failureThreshold: 20
          initialDelaySeconds: 180
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: '2'
            memory: 6Gi
          requests:
            cpu: 100m
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/gitlab
          name: gitlab-data
        - mountPath: /etc/gitlab
          name: gitlab-config
      dnsPolicy: ClusterFirst
      nodeSelector:
        workload-type: production
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config
