apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alertmanager-k8sops-online-tls
  namespace: monitoring
spec:
  secretName: alertmanager-k8sops-online-tls
  issuerRef:
    name: letsencrypt-prod-dns01
    kind: ClusterIssuer
  dnsNames:
  - alertmanager.k8sops.online

