apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"plantuml","namespace":"default"},"spec":{"ports":[{"port":8080,"targetPort":8080}],"selector":{"app":"plantuml"},"type":"ClusterIP"}}

      '
  name: plantuml
  namespace: default
spec:
  clusterIP: 10.98.166.187
  clusterIPs:
  - 10.98.166.187
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: plantuml
  sessionAffinity: None
  type: ClusterIP
